import { lato } from "@/app/ui/fonts";
import "@/app/ui/globals.css";

export const metadata = {
  title: "my-profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
